"""Initial Migration

Revision ID: 6bb899b696c1
Revises: 
Create Date: 2023-01-14 16:16:24.229424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bb899b696c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cats',
    sa.Column('CatsID', sa.Integer(), nullable=False),
    sa.Column('txtCatName', sa.String(length=200), nullable=False),
    sa.Column('txtCatGender', sa.String(length=200), nullable=False),
    sa.Column('txtCatAbout', sa.String(length=6000), nullable=False),
    sa.Column('txtCatImg', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('CatsID')
    )
    op.create_table('donationsimg',
    sa.Column('DonationimgID', sa.Integer(), nullable=False),
    sa.Column('txtDontionimg', sa.String(length=200), nullable=False),
    sa.Column('txtAlt', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('DonationimgID')
    )
    op.create_table('jobs',
    sa.Column('JobsID', sa.Integer(), nullable=False),
    sa.Column('txtJobName', sa.String(length=200), nullable=False),
    sa.Column('txtJobdes', sa.String(length=6000), nullable=False),
    sa.Column('txtJobpic', sa.String(length=200), nullable=False),
    sa.Column('txtImgalt', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('JobsID')
    )
    op.create_table('useremail',
    sa.Column('NewletterID', sa.Integer(), nullable=False),
    sa.Column('txtEmail', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('NewletterID'),
    sa.UniqueConstraint('txtEmail')
    )
    op.create_table('jobopen',
    sa.Column('JobopenID', sa.Integer(), nullable=False),
    sa.Column('JobID', sa.Integer(), nullable=False),
    sa.Column('txtDate', sa.String(length=200), nullable=False),
    sa.Column('txtTime', sa.String(length=200), nullable=False),
    sa.Column('intPartySize', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['JobID'], ['jobs.JobsID'], ),
    sa.PrimaryKeyConstraint('JobopenID')
    )
    op.create_table('job_contact',
    sa.Column('JobopenContactID', sa.Integer(), nullable=False),
    sa.Column('JobopenID', sa.Integer(), nullable=False),
    sa.Column('txtEmail', sa.String(length=200), nullable=True),
    sa.Column('txtName', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['JobopenID'], ['jobopen.JobopenID'], ),
    sa.PrimaryKeyConstraint('JobopenContactID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_contact')
    op.drop_table('jobopen')
    op.drop_table('useremail')
    op.drop_table('jobs')
    op.drop_table('donationsimg')
    op.drop_table('cats')
    # ### end Alembic commands ###
